/**
 * Default TYT / AYT ders ve konu verileri.
 * Hem prisma/seed.ts hem de auto-seed (db.ts) tarafından kullanılır.
 */

export interface SeedLesson {
    name: string;
    subjects: string[];
}

export const DEFAULT_LESSONS: SeedLesson[] = [
    // ─── TYT ────────────────────────────────────────────────
    {
        name: "TYT Türkçe",
        subjects: [
            "Sözcükte Anlam",
            "Cümlede Anlam",
            "Paragraf",
            "Paragrafta Anlatım Teknikleri",
            "Paragrafta Düşünceyi Geliştirme Yolları",
            "Paragrafta Yapı",
            "Paragrafta Konu-Ana Düşünce",
            "Paragrafta Yardımcı Düşünce",
            "Ses Bilgisi",
            "Yazım Kuralları",
            "Noktalama İşaretleri",
            "Sözcükte Yapı",
            "Sözcük Türleri",
            "İsimler",
            "Zamirler",
            "Sıfatlar",
            "Zarflar",
            "Edat – Bağlaç – Ünlem",
            "Fiiller",
            "Fiilde Anlam (Kip-Kişi-Yapı)",
            "Ek Fiil",
            "Fiilimsi",
            "Fiilde Çatı",
            "Cümlenin Ögeleri",
            "Cümle Türleri",
            "Anlatım Bozukluğu",
        ],
    },
    {
        name: "TYT Matematik",
        subjects: [
            "Temel Kavramlar",
            "Sayı Basamakları",
            "Bölme ve Bölünebilme",
            "EBOB – EKOK",
            "Rasyonel Sayılar",
            "Basit Eşitsizlikler",
            "Mutlak Değer",
            "Üslü Sayılar",
            "Köklü Sayılar",
            "Çarpanlara Ayırma",
            "Oran Orantı",
            "Denklem Çözme",
            "Problemler",
            "Sayı Problemleri",
            "Kesir Problemleri",
            "Yaş Problemleri",
            "Yüzde Problemleri",
            "Kar Zarar Problemleri",
            "Karışım Problemleri",
            "Hareket Problemleri",
            "İşçi Problemleri",
            "Tablo-Grafik Problemleri",
            "Rutin Olmayan Problemleri",
            "Kümeler",
            "Mantık",
            "Fonskiyonlar",
            "Polinomlar",
            "2.Dereceden Denklemler",
            "Permütasyon ve Kombinasyon",
            "Olasılık",
            "Veri – İstatistik",
        ],
    },
    {
        name: "TYT Geometri",
        subjects: [
            "Doğruda Açı",
            "Üçgende Açı",
            "Ek Çizimler",
            "Özel Üçgenler",
            "Dik Üçgen",
            "İkizkenar Üçgen",
            "Eşkenar Üçgen",
            "Açıortay",
            "Kenarortay",
            "Üçgende Eşlik – Benzerlik",
            "Açı – Kenar Bağıntıları",
            "Üçgende Alan",
            "Üçgende Merkezler",
            "Çokgenler",
            "Dörtgenler",
            "Deltoid",
            "Paralelkenar",
            "Eşkenar Dörtgen",
            "Dikdörtgen",
            "Kare",
            "Yamuk",
            "Çember ve Daire",
            "Çemberde Açı",
            "Çemberde Uzunluk",
            "Dairede Alan",
            "Analitik Geometri",
            "Noktanın Analitiği",
            "Doğrunun Analitiği",
            "Katı Cisimler",
            "Prizmalar",
            "Küp",
            "Silindir",
            "Piramit",
            "Koni",
            "Küre",
        ],
    },
    {
        name: "TYT Fizik",
        subjects: [
            "Fizik Bilimine Giriş",
            "Madde ve Özellikleri",
            "Hareket ve Kuvvet",
            "İş, Güç ve Enerji",
            "Isı, Sıcaklık ve Genleşme",
            "Basınç",
            "Kaldırma Kuvveti",
            "Elektrostatik",
            "Elektrik ve Manyetizma",
            "Dalgalar",
            "Optik",
        ],
    },
    {
        name: "TYT Kimya",
        subjects: [
            "Kimya Bilimi",
            "Atom ve Periyodik Sistem",
            "Kimyasal Türler Arası Etkileşimler",
            "Maddenin Halleri",
            "Doğa ve Kimya",
            "Kimyanın Temel Kanunları",
            "Kimyasal Hesaplamalar",
            "Karışımlar",
            "Asit, Baz ve Tuz",
            "Kimya Her Yerde",
        ],
    },
    {
        name: "TYT Biyoloji",
        subjects: [
            "Canlıların Ortak Özellikleri",
            "Canlıların Temel Bileşenleri",
            "Hücre ve Organelleri",
            "Hücre Zarından Madde Geçişi",
            "Canlıların Sınıflandırılması",
            "Mitoz ve Eşeysiz Üreme",
            "Mayoz ve Eşeyli Üreme",
            "Kalıtım",
            "Ekosistem Ekolojisi",
            "Güncel Çevre Sorunları",
        ],
    },
    {
        name: "TYT Tarih",
        subjects: [
            "Tarih ve Zaman",
            "İnsanlığın İlk Dönemleri",
            "İlk ve Orta Çağlarda Türk Dünyası",
            "İslam Medeniyetinin Doğuşu ve İlk İslam Devletleri",
            "Türklerin İslamiyet'i Kabulü ve İlk Türk İslam Devletleri",
            "Orta Çağ'da Dünya",
            "Yerleşme ve Devletleşme Sürecinde Selçuklu Türkiyesi",
            "Beylikten Devlete Osmanlı Siyaseti",
            "Devletleşme Sürecinde Savaşçılar ve Askerler",
            "Beylikten Devlete Osmanlı Medeniyeti",
            "Dünya Gücü Osmanlı",
            "Sultan ve Osmanlı Merkez Teşkilatı",
            "Klasik Çağda Osmanlı Toplum Düzeni",
            "Değişen Dünya Dengeleri Karşısında Osmanlı Siyaseti",
            "Değişim Çağında Avrupa ve Osmanlı",
            "Uluslararası İlişkilerde Denge Stratejisi (1774-1914)",
            "Devrimler Çağında Değişen Devlet-Toplum İlişkileri",
            "Sermaye ve Emek",
            "XIX. ve XX. Yüzyılda Değişen Gündelik Hayat",
            "XX. Yüzyıl Başlarında Osmanlı Devleti ve Dünya",
            "Milli Mücadele",
            "Atatürkçülük ve Türk İnkılabı",
        ],
    },
    {
        name: "TYT Coğrafya",
        subjects: [
            "Doğa ve İnsan",
            "Dünya'nın Şekli ve Hareketleri",
            "Coğrafi Konum",
            "Harita Bilgisi",
            "İklim Bilgisi",
            "Dünya'nın Tektonik Oluşumu",
            "Jeolojik Zamanlar",
            "İç Kuvvetler / Dış Kuvvetler",
            "Kayaçlar",
            "Türkiye'nin Yer Şekilleri",
            "Su – Toprak ve Bitkiler",
            "Nüfus",
            "Türkiye'de Nüfus",
            "Göç",
            "Ekonomik Faaliyetler",
            "Bölgeler",
            "Uluslararası Ulaşım Hatları",
            "Çevre ve Toplum",
            "Doğal Afetler",
        ],
    },
    {
        name: "TYT Felsefe",
        subjects: [
            "Felsefe'nin Konusu",
            "Bilgi Felsefesi",
            "Varlık Felsefesi",
            "Ahlak Felsefesi",
            "Sanat Felsefesi",
            "Din Felsefesi",
            "Siyaset Felsefesi",
            "Bilim Felsefesi",
            "İlk Çağ Felsefesi",
            "2. Yüzyıl ve 15. Yüzyıl Felsefeleri",
            "15. Yüzyıl ve 17. Yüzyıl Felsefeleri",
            "18. Yüzyıl ve 19. Yüzyıl Felsefeleri",
            "20. Yüzyıl Felsefesi",
        ],
    },
    {
        name: "TYT Din Kültürü",
        subjects: [
            "Bilgi ve İnanç",
            "Din ve İslam",
            "İslam ve İbadet",
            "Gençlik ve Değerler",
            "İslam Medeniyeti ve Özellikleri",
            "Allah İnancı ve İnsan",
            "Allah'ın Varlığı ve Birliği",
            "Allah'ın İsim ve Sıfatları",
            "Kur'an-ı Kerim'de İnsan ve Özellikleri",
            "İnsanın Allah İle İrtibatı",
            "Kur'an-ı Kerim'de Gençler",
            "Bir Genç Olarak Hz. Muhammed",
            "Hz. Muhammed ve Gençler",
            "Bazı Genç Sahabiler",
            "Din ve Aile",
            "Din, Kültür ve Sanat",
            "Din ve Çevre",
            "Din ve Sosyal Değişim",
            "Din ve Ekonomi",
            "Din ve Sosyal Adalet",
            "Ahlaki Tutum ve Davranışlar",
            "İslam Düşüncesinde İtikadi, Siyasi ve Fıkhi Yorumlar",
        ],
    },

    // ─── AYT ────────────────────────────────────────────────
    {
        name: "AYT Matematik",
        subjects: [
            "Temel Kavramlar",
            "Sayı Basamakları",
            "Bölme ve Bölünebilme",
            "EBOB – EKOK",
            "Rasyonel Sayılar",
            "Basit Eşitsizlikler",
            "Mutlak Değer",
            "Üslü Sayılar",
            "Köklü Sayılar",
            "Çarpanlara Ayırma",
            "Oran Orantı",
            "Denklem Çözme",
            "Problemler",
            "Kümeler",
            "Mantık",
            "Fonskiyonlar",
            "Polinomlar",
            "2.Dereceden Denklemler",
            "Binom",
            "Permütasyon ve Kombinasyon",
            "Olasılık",
            "Veri – İstatistik",
            "Karmaşık Sayılar",
            "2.Dereceden Eşitsizlikler",
            "Parabol",
            "Trigonometri",
            "Logaritma",
            "Diziler",
            "Limit",
            "Türev",
            "İntegral",
        ],
    },
    {
        name: "AYT Geometri",
        subjects: [
            "Doğruda Açı",
            "Üçgende Açı",
            "Ek Çizimler",
            "Özel Üçgenler",
            "Dik Üçgen",
            "İkizkenar Üçgen",
            "Eşkenar Üçgen",
            "Açıortay",
            "Kenarortay",
            "Üçgende Eşlik – Benzerlik",
            "Açı – Kenar Bağıntıları",
            "Üçgende Alan",
            "Üçgende Merkezler",
            "Çokgenler",
            "Özel Dörtgenler",
            "Dörtgenler",
            "Deltoid",
            "Paralelkenar",
            "Eşkenar Dörtgen",
            "Dikdörtgen",
            "Kare",
            "İkizkenar Yamuk",
            "Yamuk",
            "Çember ve Daire",
            "Analitik Geometri",
            "Noktanın Analitiği",
            "Doğrunun Analitiği",
            "Dönüşüm Geometrisi",
            "Katı Cisimler (Uzay Geometri)",
            "Prizmalar",
            "Küp",
            "Silindir",
            "Piramit",
            "Koni",
            "Küre",
            "Çemberin Analitiği",
        ],
    },
    {
        name: "AYT Fizik",
        subjects: [
            "Vektörler",
            "Kuvvet, Tork ve Denge",
            "Kütle Merkezi",
            "Basit Makineler",
            "Hareket",
            "Newton'un Hareket Yasaları",
            "İş, Güç ve Enerji",
            "Atışlar",
            "İtme ve Momentum",
            "Elektrik Alan ve Potansiyel",
            "Paralel Levhalar ve Sığa",
            "Manyetik Alan ve Manyetik Kuvvet",
            "İndüksiyon, Alternatif Akım ve Transformatörler",
            "Düzgün Çembersel Hareket",
            "Dönme, Yuvarlanma ve Açısal Momentum",
            "Kütle Çekim ve Kepler Yasaları",
            "Basit Harmonik Hareket",
            "Dalga Mekaniği",
            "Atom Fiziğine Giriş ve Radyoaktivite",
            "Modern Fizik",
            "Modern Fiziğin Teknolojideki Uygulamaları",
        ],
    },
    {
        name: "AYT Kimya",
        subjects: [
            "Kimya Bilimi",
            "Atom ve Periyodik Sistem",
            "Kimyasal Türler Arası Etkileşimler",
            "Kimyasal Hesaplamalar",
            "Kimyanın Temel Kanunları",
            "Asit, Baz ve Tuz",
            "Maddenin Halleri",
            "Karışımlar",
            "Doğa ve Kimya",
            "Kimya Her Yerde",
            "Modern Atom Teorisi",
            "Gazlar",
            "Sıvı Çözeltiler ve Çözünürlük",
            "Kimyasal Tepkimelerde Enerji",
            "Kimyasal Tepkimelerde Hız",
            "Kimyasal Tepkimelerde Denge",
            "Asit-Baz Dengesi",
            "Çözünürlük Dengesi",
            "Kimya ve Elektrik",
            "Karbon Kimyasına Giriş",
            "Organik Kimya",
            "Enerji Kaynakları ve Bilimsel Gelişmeler",
        ],
    },
    {
        name: "AYT Biyoloji",
        subjects: [
            "Sinir Sistemi",
            "Endokrin Sistem",
            "Duyu Organları",
            "Destek ve Hareket Sistemi",
            "Sindirim Sistemi",
            "Dolaşım ve Bağışıklık Sistemi",
            "Solunum Sistemi",
            "Üriner Sistem (Boşaltım Sistemi)",
            "Üreme Sistemi ve Embriyonik Gelişim",
            "Komünite Ekolojisi",
            "Popülasyon Ekolojisi",
            "Genden Proteine",
            "Nükleik Asitler",
            "Genetik Şifre ve Protein Sentezi",
            "Canlılarda Enerji Dönüşümleri",
            "Canlılık ve Enerji",
            "Fotosentez",
            "Kemosentez",
            "Hücresel Solunum",
            "Bitki Biyolojisi",
            "Canlılar ve Çevre",
        ],
    },
    {
        name: "AYT Edebiyat",
        subjects: [
            "Anlam Bilgisi",
            "Şiir Bilgisi",
            "Söz Sanatları",
            "Türk Edebiyatı Dönemleri",
            "İslamiyet Öncesi Türk Edebiyatı ve Geçiş Dönemi",
            "Halk Edebiyatı",
            "Divan Edebiyatı",
            "Tanzimat Edebiyatı",
            "Servet-i Fünun Edebiyatı",
            "Fecr-i Ati Edebiyatı",
            "Milli Edebiyat",
            "Cumhuriyet Dönemi Edebiyatı",
            "Dünya Edebiyatı",
            "Edebi Akımlar",
            "Roman Özetleri",
        ],
    },
    {
        name: "AYT Coğrafya",
        subjects: [
            "Ekosistemlerin Özellikleri ve İşleyişi",
            "Biyoçeşitlilik",
            "Ekosistemlerin Unsurları",
            "Enerji Akışı ve Madde Döngüleri",
            "Su Ekosistemleri",
            "Ekstrem Doğa Olayları",
            "Doğa ve Değişim",
            "Küresel İklim Değişimi",
            "Nüfus Politikaları",
            "Yerleşmelerin Özellikleri",
            "Ekonomik Faaliyetler ve Doğal Kaynaklar",
            "Türkiye'de Ekonomi",
            "Geçmişten Geleceğe Şehir ve Ekonomi",
            "Türkiye'nin İşlevsel Bölgeleri ve Kalkınma Projeleri",
            "Hizmet Sektörünün Ekonomideki Yeri",
            "Küresel Ticaret",
            "Türkiye Turizmi",
            "Kültür Bölgeleri",
            "Jeopolitik Konum",
            "Ülkeler Arası Etkileşim",
            "Çevre ve Toplum",
            "Çevre Sorunları ve Türleri",
            "Madenler ve Enerji Kaynaklarına Ait Kullanımın Çevresel Etkileri",
            "Doğal Kaynak Kullanımının Çevresel Etkileri",
            "Arazi Kullanımının Çevresel Etkileri",
            "Küresel Çevre Sorunları",
            "Doğal Kaynakların Sürdürülebilir Kullanımı",
            "Doğal Çevrenin Sınırlılığı",
            "Çevre Politikaları",
            "Çevresel Örgütler ve Çevre Anlaşmaları",
            "Ortak Doğal ve Kültürel Mirasa Yönelik Tehditler",
        ],
    },
    {
        name: "AYT Tarih",
        subjects: [
            "Tarih ve Zaman",
            "İnsanlığın İlk Dönemleri",
            "İlk ve Orta Çağlarda Türk Dünyası",
            "İslam Medeniyetinin Doğuşu ve İlk İslam Devletleri",
            "Türklerin İslamiyet'i Kabulü ve İlk Türk İslam Devletleri",
            "Orta Çağ'da Dünya",
            "Yerleşme ve Devletleşme Sürecinde Selçuklu Türkiyesi",
            "Beylikten Devlete Osmanlı Siyaseti",
            "Devletleşme Sürecinde Savaşçılar ve Askerler",
            "Beylikten Devlete Osmanlı Medeniyeti",
            "Dünya Gücü Osmanlı",
            "Sultan ve Osmanlı Merkez Teşkilatı",
            "Klasik Çağda Osmanlı Toplum Düzeni",
            "Değişen Dünya Dengeleri Karşısında Osmanlı Siyaseti",
            "Değişim Çağında Avrupa ve Osmanlı",
            "Uluslararası İlişkilerde Denge Stratejisi (1774-1914)",
            "Devrimler Çağında Değişen Devlet-Toplum İlişkileri",
            "Sermaye ve Emek",
            "XIX. ve XX. Yüzyılda Değişen Gündelik Hayat",
            "XX. Yüzyıl Başlarında Osmanlı Devleti ve Dünya",
            "Milli Mücadele",
            "Atatürkçülük ve Türk İnkılabı",
            "İki Savaş Arasındaki Dönemde Türkiye ve Dünya",
            "II. Dünya Savaşı Sürecinde Türkiye ve Dünya",
            "II. Dünya Savaşı Sonrasında Türkiye ve Dünya",
            "Toplumsal Devrim Çağında Dünya ve Türkiye",
            "XXI. Yüzyılın Eşiğinde Türkiye ve Dünya",
        ],
    },
    {
        name: "AYT Felsefe",
        subjects: [
            "Felsefe'nin Konusu",
            "Bilgi Felsefesi",
            "Varlık Felsefesi",
            "Ahlak Felsefesi",
            "Sanat Felsefesi",
            "Din Felsefesi",
            "Siyaset Felsefesi",
            "Bilim Felsefesi",
            "İlk Çağ Felsefesi",
            "MÖ 6. Yüzyıl – MS 2. Yüzyıl Felsefesi",
            "MS 2. Yüzyıl – MS 15. Yüzyıl Felsefesi",
            "15. Yüzyıl – 17. Yüzyıl Felsefesi",
            "18. Yüzyıl – 19. Yüzyıl Felsefesi",
            "20. Yüzyıl Felsefesi",
        ],
    },
    {
        name: "AYT Mantık",
        subjects: [
            "Mantığa Giriş",
            "Klasik Mantık",
            "Mantık ve Dil",
            "Sembolik Mantık",
        ],
    },
    {
        name: "AYT Psikoloji",
        subjects: [
            "Psikoloji Bilimini Tanıyalım",
            "Psikolojinin Temel Süreçleri",
            "Öğrenme Bellek Düşünme",
            "Ruh Sağlığının Temelleri",
        ],
    },
    {
        name: "AYT Sosyoloji",
        subjects: [
            "Sosyolojiye Giriş",
            "Birey ve Toplum",
            "Toplumsal Yapı",
            "Toplumsal Değişme ve Gelişme",
            "Toplum ve Kültür",
            "Toplumsal Kurumlar",
        ],
    },
    {
        name: "AYT Din Kültürü ve Ahlak Bilgisi",
        subjects: [
            "Dünya ve Ahiret",
            "Kur'an'a Göre Hz. Muhammed",
            "Kur'an'da Bazı Kavramlar",
            "İnançla İlgili Meseleler",
            "Yahudilik ve Hristiyanlık",
            "İslam ve Bilim",
            "Anadolu'da İslam",
            "İslam Düşüncesinde Tasavvufi Yorumlar",
            "Güncel Dini Meseleler",
            "Hint ve Çin Dinleri",
        ],
    },
];
